apiVersion: v1
kind: Pod
metadata:
  name: secondapp  # The name of the Pod, used to uniquely identify it within the namespace
spec:
  securityContext:
    runAsUser: 1000  # The user ID to run the Pod as
  containers:
    - name: busy  # The name of the container
      image: busybox  # The container image to be used
      command:
        - sleep
        - "3600"
      securityContext:
        runAsUser: 2000  # The user ID to run the container as
        allowPrivilegeEscalation: false  # Prevent privilege escalation
        capabilities:                       
          add: ["NET_ADMIN","SYS_TIME"]  # Add NET_ADMIN and SYS_TIME capabilities to the container, allowing it to manage network interfaces and system time
      volumeMounts:                        
        - name: mysql  # Name of the volume mount
          mountPath: /mysqlpassword  # Path where the secret will be mounted inside the container
  volumes:
    - name: mysql  # Name of the volume
      secret:
        secretName: lfsecret  # Reference to the secret named 'lfsecret'